import { neon } from '@neondatabase/serverless';

let schemaReady = false;

export function db() {
  return neon(process.env.DATABASE_URL);
}

export async function ensureSchema(sql) {
  if (schemaReady) return;
  await sql`
    CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      name TEXT NOT NULL,
      password_hash TEXT NOT NULL,
      verified BOOLEAN NOT NULL DEFAULT FALSE,
      address JSONB,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;
  await sql`
    CREATE TABLE IF NOT EXISTS verification_codes (
      email TEXT PRIMARY KEY,
      code TEXT NOT NULL,
      expires_at TIMESTAMPTZ NOT NULL
    )
  `;
  await sql`
    CREATE TABLE IF NOT EXISTS products (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT NOT NULL DEFAULT '',
      price_paise INTEGER NOT NULL,
      image_url TEXT NOT NULL DEFAULT '',
      customizable BOOLEAN NOT NULL DEFAULT FALSE,
      custom_label TEXT NOT NULL DEFAULT 'Your message',
      in_stock BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;
  await sql`
    CREATE TABLE IF NOT EXISTS orders (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL REFERENCES users(id),
      items JSONB NOT NULL,
      address JSONB NOT NULL,
      total_paise INTEGER NOT NULL,
      upi_ref TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'pending',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;
  await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMPTZ`;
  await sql`ALTER TABLE orders ADD COLUMN IF NOT EXISTS courier TEXT`;
  await sql`ALTER TABLE orders ADD COLUMN IF NOT EXISTS tracking_id TEXT`;
  // Date the UPI payment was made (customer-supplied) and the date the order was shipped (admin-stamped).
  await sql`ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_at DATE`;
  await sql`ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipped_at DATE`;
  // Admin's reason/comment captured when marking an order fulfilled or cancelled.
  await sql`ALTER TABLE orders ADD COLUMN IF NOT EXISTS status_note TEXT`;
  await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '[]'`;
  // Up to 3 photos per product; images[0] is the cover shown on cards.
  await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS images JSONB NOT NULL DEFAULT '[]'`;
  // Admin-curated pick for the "Featured Keepsakes" section on the home page.
  await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS featured BOOLEAN NOT NULL DEFAULT FALSE`;
  // Fixed-size crop of the cover photo, set only when the admin runs it through the
  // crop tool — never falls back to a legacy/uncropped image. Empty means the shop
  // grid shows no photo for that product until it's (re-)cropped.
  await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS thumb_url TEXT NOT NULL DEFAULT ''`;
  // Optional size/variant options, e.g. [{label:"8x10", price_paise:49900}]. When present,
  // price_paise on the product row is kept as the cheapest dimension (used for card/list display).
  await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS dimensions JSONB NOT NULL DEFAULT '[]'`;
  // Human-facing numeric order number (#1001, #1002, …); existing rows are backfilled.
  await sql`ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_no BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001)`;
  // Manual display-order rank for the shop grid — lower shows first. New products default
  // to the bottom (MAX+1 on insert); existing rows are backfilled once here, newest-first,
  // so nothing visibly reshuffles on deploy. The admin can then drag/rank them from there.
  await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS sort_order BIGINT`;
  await sql`
    UPDATE products p SET sort_order = sub.rn
    FROM (SELECT id, ROW_NUMBER() OVER (ORDER BY created_at DESC) AS rn FROM products WHERE sort_order IS NULL) sub
    WHERE p.id = sub.id AND p.sort_order IS NULL
  `;
  await sql`
    CREATE TABLE IF NOT EXISTS reviews (
      id TEXT PRIMARY KEY,
      product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
      user_id TEXT NOT NULL REFERENCES users(id),
      user_name TEXT NOT NULL,
      rating INTEGER NOT NULL,
      text TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'pending',
      featured BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;

  // ─── One-time migration: UUID text ids → numeric ids ──────────────────────
  // Each block is a single atomic statement (DO $$ ... $$), so a failure rolls back
  // that table's migration entirely — no partial state. Each is self-guarded (skips
  // if already numeric), so it's safe to run on every cold start. The original UUID
  // is kept as `legacy_id` (never dropped) so nothing is destroyed. Dependents that
  // stored the old UUID (FKs, and orders.items[].productId inside JSONB) are remapped
  // to the new numeric id before the old id is retired, so existing links keep working.

  // products.id — remaps reviews.product_id and orders.items[].productId
  await sql`
    DO $$
    DECLARE pk_name text;
    BEGIN
      IF (SELECT data_type FROM information_schema.columns WHERE table_name = 'products' AND column_name = 'id') = 'text' THEN
        ALTER TABLE products ADD COLUMN numeric_id BIGINT;
        UPDATE products p SET numeric_id = sub.rn
          FROM (SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS rn FROM products) sub
          WHERE p.id = sub.id;
        ALTER TABLE products ALTER COLUMN numeric_id SET NOT NULL;

        ALTER TABLE reviews DROP CONSTRAINT IF EXISTS reviews_product_id_fkey;

        UPDATE reviews r SET product_id = p.numeric_id::text
          FROM products p WHERE r.product_id = p.id;

        UPDATE orders o SET items = sub.new_items
          FROM (
            SELECT o2.id AS order_id, jsonb_agg(
              CASE WHEN p.numeric_id IS NOT NULL
                THEN (elem - 'productId') || jsonb_build_object('productId', p.numeric_id::text)
                ELSE elem END
              ORDER BY ord
            ) AS new_items
            FROM orders o2
            CROSS JOIN LATERAL jsonb_array_elements(o2.items) WITH ORDINALITY AS t(elem, ord)
            LEFT JOIN products p ON p.id = (elem->>'productId')
            GROUP BY o2.id
          ) sub
          WHERE o.id = sub.order_id;

        SELECT conname INTO pk_name FROM pg_constraint WHERE conrelid = 'products'::regclass AND contype = 'p';
        IF pk_name IS NOT NULL THEN
          EXECUTE format('ALTER TABLE products DROP CONSTRAINT %I', pk_name);
        END IF;

        ALTER TABLE products RENAME COLUMN id TO legacy_id;
        ALTER TABLE products RENAME COLUMN numeric_id TO id;
        ALTER TABLE products ADD PRIMARY KEY (id);

        CREATE SEQUENCE IF NOT EXISTS products_id_seq OWNED BY products.id;
        PERFORM setval('products_id_seq', COALESCE((SELECT MAX(id) FROM products), 0) + 1, false);
        ALTER TABLE products ALTER COLUMN id SET DEFAULT nextval('products_id_seq');

        ALTER TABLE reviews ALTER COLUMN product_id TYPE BIGINT USING product_id::bigint;
        ALTER TABLE reviews ADD CONSTRAINT reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
      END IF;
    END $$;
  `;

  // users.id — remaps orders.user_id and reviews.user_id. Note: existing login
  // tokens embed the old UUID as `uid`; after this runs, anyone already logged in
  // needs to log in again once (the new numeric id won't match their old token).
  await sql`
    DO $$
    DECLARE pk_name text;
    BEGIN
      IF (SELECT data_type FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'id') = 'text' THEN
        ALTER TABLE users ADD COLUMN numeric_id BIGINT;
        UPDATE users u SET numeric_id = sub.rn
          FROM (SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS rn FROM users) sub
          WHERE u.id = sub.id;
        ALTER TABLE users ALTER COLUMN numeric_id SET NOT NULL;

        ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_user_id_fkey;
        ALTER TABLE reviews DROP CONSTRAINT IF EXISTS reviews_user_id_fkey;

        UPDATE orders o SET user_id = u.numeric_id::text FROM users u WHERE o.user_id = u.id;
        UPDATE reviews r SET user_id = u.numeric_id::text FROM users u WHERE r.user_id = u.id;

        SELECT conname INTO pk_name FROM pg_constraint WHERE conrelid = 'users'::regclass AND contype = 'p';
        IF pk_name IS NOT NULL THEN
          EXECUTE format('ALTER TABLE users DROP CONSTRAINT %I', pk_name);
        END IF;

        ALTER TABLE users RENAME COLUMN id TO legacy_id;
        ALTER TABLE users RENAME COLUMN numeric_id TO id;
        ALTER TABLE users ADD PRIMARY KEY (id);

        CREATE SEQUENCE IF NOT EXISTS users_id_seq OWNED BY users.id;
        PERFORM setval('users_id_seq', COALESCE((SELECT MAX(id) FROM users), 0) + 1, false);
        ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_id_seq');

        ALTER TABLE orders ALTER COLUMN user_id TYPE BIGINT USING user_id::bigint;
        ALTER TABLE reviews ALTER COLUMN user_id TYPE BIGINT USING user_id::bigint;
        ALTER TABLE orders ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
        ALTER TABLE reviews ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id);
      END IF;
    END $$;
  `;

  // orders.id — nothing else references it, so this is a simple in-place swap.
  await sql`
    DO $$
    DECLARE pk_name text;
    BEGIN
      IF (SELECT data_type FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'id') = 'text' THEN
        ALTER TABLE orders ADD COLUMN numeric_id BIGINT;
        UPDATE orders o SET numeric_id = sub.rn
          FROM (SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS rn FROM orders) sub
          WHERE o.id = sub.id;
        ALTER TABLE orders ALTER COLUMN numeric_id SET NOT NULL;

        SELECT conname INTO pk_name FROM pg_constraint WHERE conrelid = 'orders'::regclass AND contype = 'p';
        IF pk_name IS NOT NULL THEN
          EXECUTE format('ALTER TABLE orders DROP CONSTRAINT %I', pk_name);
        END IF;

        ALTER TABLE orders RENAME COLUMN id TO legacy_id;
        ALTER TABLE orders RENAME COLUMN numeric_id TO id;
        ALTER TABLE orders ADD PRIMARY KEY (id);

        CREATE SEQUENCE IF NOT EXISTS orders_id_seq OWNED BY orders.id;
        PERFORM setval('orders_id_seq', COALESCE((SELECT MAX(id) FROM orders), 0) + 1, false);
        ALTER TABLE orders ALTER COLUMN id SET DEFAULT nextval('orders_id_seq');
      END IF;
    END $$;
  `;

  // reviews.id — nothing else references it, so this is a simple in-place swap.
  await sql`
    DO $$
    DECLARE pk_name text;
    BEGIN
      IF (SELECT data_type FROM information_schema.columns WHERE table_name = 'reviews' AND column_name = 'id') = 'text' THEN
        ALTER TABLE reviews ADD COLUMN numeric_id BIGINT;
        UPDATE reviews r SET numeric_id = sub.rn
          FROM (SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS rn FROM reviews) sub
          WHERE r.id = sub.id;
        ALTER TABLE reviews ALTER COLUMN numeric_id SET NOT NULL;

        SELECT conname INTO pk_name FROM pg_constraint WHERE conrelid = 'reviews'::regclass AND contype = 'p';
        IF pk_name IS NOT NULL THEN
          EXECUTE format('ALTER TABLE reviews DROP CONSTRAINT %I', pk_name);
        END IF;

        ALTER TABLE reviews RENAME COLUMN id TO legacy_id;
        ALTER TABLE reviews RENAME COLUMN numeric_id TO id;
        ALTER TABLE reviews ADD PRIMARY KEY (id);

        CREATE SEQUENCE IF NOT EXISTS reviews_id_seq OWNED BY reviews.id;
        PERFORM setval('reviews_id_seq', COALESCE((SELECT MAX(id) FROM reviews), 0) + 1, false);
        ALTER TABLE reviews ALTER COLUMN id SET DEFAULT nextval('reviews_id_seq');
      END IF;
    END $$;
  `;

  schemaReady = true;
}
