import { neon } from '@neondatabase/serverless';

let schemaReady = false;

export function db() {
  return neon(process.env.DATABASE_URL);
}

export async function ensureSchema(sql) {
  if (schemaReady) return;
  await sql`
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      name TEXT NOT NULL,
      password_hash TEXT NOT NULL,
      verified BOOLEAN NOT NULL DEFAULT FALSE,
      address JSONB,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;
  await sql`
    CREATE TABLE IF NOT EXISTS verification_codes (
      email TEXT PRIMARY KEY,
      code TEXT NOT NULL,
      expires_at TIMESTAMPTZ NOT NULL
    )
  `;
  await sql`
    CREATE TABLE IF NOT EXISTS products (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT NOT NULL DEFAULT '',
      price_paise INTEGER NOT NULL,
      image_url TEXT NOT NULL DEFAULT '',
      customizable BOOLEAN NOT NULL DEFAULT FALSE,
      custom_label TEXT NOT NULL DEFAULT 'Your message',
      in_stock BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;
  await sql`
    CREATE TABLE IF NOT EXISTS orders (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id),
      items JSONB NOT NULL,
      address JSONB NOT NULL,
      total_paise INTEGER NOT NULL,
      upi_ref TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'pending',
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;
  await sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMPTZ`;
  await sql`ALTER TABLE orders ADD COLUMN IF NOT EXISTS courier TEXT`;
  await sql`ALTER TABLE orders ADD COLUMN IF NOT EXISTS tracking_id TEXT`;
  // Date the UPI payment was made (customer-supplied) and the date the order was shipped (admin-stamped).
  await sql`ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_at DATE`;
  await sql`ALTER TABLE orders ADD COLUMN IF NOT EXISTS shipped_at DATE`;
  // Admin's reason/comment captured when marking an order fulfilled or cancelled.
  await sql`ALTER TABLE orders ADD COLUMN IF NOT EXISTS status_note TEXT`;
  await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS tags JSONB NOT NULL DEFAULT '[]'`;
  // Up to 3 photos per product; images[0] is the cover shown on cards.
  await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS images JSONB NOT NULL DEFAULT '[]'`;
  // Admin-curated pick for the "Featured Keepsakes" section on the home page.
  await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS featured BOOLEAN NOT NULL DEFAULT FALSE`;
  // Fixed-size crop of the cover photo, set only when the admin runs it through the
  // crop tool — never falls back to a legacy/uncropped image. Empty means the shop
  // grid shows no photo for that product until it's (re-)cropped.
  await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS thumb_url TEXT NOT NULL DEFAULT ''`;
  // Optional size/variant options, e.g. [{label:"8x10", price_paise:49900}]. When present,
  // price_paise on the product row is kept as the cheapest dimension (used for card/list display).
  await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS dimensions JSONB NOT NULL DEFAULT '[]'`;
  // Human-facing numeric order number (#1001, #1002, …); existing rows are backfilled.
  await sql`ALTER TABLE orders ADD COLUMN IF NOT EXISTS order_no BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001)`;
  // Manual display-order rank for the shop grid — lower shows first. New products default
  // to the bottom (MAX+1 on insert); existing rows are backfilled once here, newest-first,
  // so nothing visibly reshuffles on deploy. The admin can then drag/rank them from there.
  await sql`ALTER TABLE products ADD COLUMN IF NOT EXISTS sort_order BIGINT`;
  await sql`
    UPDATE products p SET sort_order = sub.rn
    FROM (SELECT id, ROW_NUMBER() OVER (ORDER BY created_at DESC) AS rn FROM products WHERE sort_order IS NULL) sub
    WHERE p.id = sub.id AND p.sort_order IS NULL
  `;
  await sql`
    CREATE TABLE IF NOT EXISTS reviews (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
      user_id BIGINT NOT NULL REFERENCES users(id),
      user_name TEXT NOT NULL,
      rating INTEGER NOT NULL,
      text TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'pending',
      featured BOOLEAN NOT NULL DEFAULT FALSE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;

  // The old text ids (from before the numeric-id migration) were kept as `legacy_id`
  // on each table as a safety net; the migration has been live long enough that
  // they're no longer needed, so drop them. IF EXISTS makes this a harmless no-op
  // once dropped.
  await sql`ALTER TABLE products DROP COLUMN IF EXISTS legacy_id`;
  await sql`ALTER TABLE users DROP COLUMN IF EXISTS legacy_id`;
  await sql`ALTER TABLE orders DROP COLUMN IF EXISTS legacy_id`;
  await sql`ALTER TABLE reviews DROP COLUMN IF EXISTS legacy_id`;

  schemaReady = true;
}
